scrape_configs:
  - job_name: 'e-learning-platform'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3001'] # Porta do endpoint de métricas


global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*):\d+'
        replacement: '${1}'

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:6379']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['localhost:27017']



# alert.rules.yml
   groups:
   - name: Critical
     rules:
     - alert: HighRejectionRate
       expr: rate(course_rejections_total[5m]) > 0.5
